apiVersion: apps/v1
kind: Deployment
metadata:
  name: munjo-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: munjo-portfolio
  template:
    metadata:
      labels:
        app: munjo-portfolio
    spec:
      containers:
        - name: munjo-portfolio
          image: munjo185/munjo-portfolio:17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: munjo-portfolio-config
                  key: APP_ENV
            - name: SITE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: munjo-portfolio-secret
                  key: SITE_API_KEY
